from enum import Enum


class Exams(Enum):
    AP_US_GOVERNMENT_AND_POLITICS = 1
    AP_COMPARATIVE_GOVERNMENT_AND_POLITICS = 2
    AP_FRENCH_LANGUAGE_AND_CULTURE = 3
    AP_COMPUTER_SCIENCE_A = 4
    AP_SPANISH_LANGUAGE_AND_CULTURE = 6
    AP_STATISTICS = 7
    AP_CALCULUS_AB = 8
    AP_CALCULUS_BC = 9
    AP_CHINESE_LANGUAGE_AND_CULTURE = 10
    AP_ENGLISH_LITERATURE_AND_COMPOSITION = 11
    AP_GERMAN_LANGUAGE_AND_CULTURE = 12
    AP_JAPANESE_LANGUAGE_AND_CULTURE = 13
    AP_US_HISTORY = 15
    AP_EUROPEAN_HISTORY = 16
    AP_BIOLOGY = 18
    AP_MUSIC_THEORY = 19
    AP_PHYSICS_C_MECHANICS = 21
    AP_PHYSICS_C_ELECTRICITY_AND_MAGNETISM = 22
    AP_ENVIRONMENTAL_SCIENCE = 23
    AP_CHEMISTRY = 24
    AP_PSYCHOLOGY = 25
    AP_ENGLISH_LANGUAGE_AND_COMPOSITION = 27
    AP_ART_HISTORY = 28
    AP_MACROECONOMICS = 29
    AP_WORLD_HISTORY = 30
    AP_MICROECONOMICS = 31
    AP_HUMAN_GEOGRAPHY = 32
    AP_SPANISH_LITERATURE_AND_CULTURE = 33
    AP_LATIN = 35
    AP_2D_ART_AND_DESIGN = 36
    AP_3D_ART_AND_DESIGN = 37
    AP_DRAWING = 38
    AP_ITALIAN_LANGUAGE_AND_CULTURE = 49
    AP_PHYSICS_1 = 50
    AP_PHYSICS_2 = 51
    AP_SEMINAR = 52
    AP_RESEARCH = 53
    AP_COMPUTER_SCIENCE_PRINCIPLES = 54
